// <auto-generated />
using DNMVCCP.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DNMVCCP.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260130095241_AddProductAndSeedTableToDb")]
    partial class AddProductAndSeedTableToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DNMVCCP.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "SciFi"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "History"
                        });
                });

            modelBuilder.Entity("DNMVCCP.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ListPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price100")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price50")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Waqas Nazir1",
                            Description = "This is my first book",
                            ISBN = "SW4345355435",
                            ListPrice = 99m,
                            Price = 90m,
                            Price100 = 50m,
                            Price50 = 85m,
                            Title = "Book1"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Waqas Nazir2",
                            Description = "This is my second book",
                            ISBN = "SW4345355435",
                            ListPrice = 99m,
                            Price = 90m,
                            Price100 = 50m,
                            Price50 = 85m,
                            Title = "Book2"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Waqas Nazir3",
                            Description = "This is my third book",
                            ISBN = "SW4345355435",
                            ListPrice = 99m,
                            Price = 90m,
                            Price100 = 50m,
                            Price50 = 85m,
                            Title = "Book3"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Waqas Nazir4",
                            Description = "This is my fourth book",
                            ISBN = "SW4345355435",
                            ListPrice = 99m,
                            Price = 90m,
                            Price100 = 50m,
                            Price50 = 85m,
                            Title = "Book4"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Waqas Nazir5",
                            Description = "This is my fifth book",
                            ISBN = "SW4345355435",
                            ListPrice = 99m,
                            Price = 90m,
                            Price100 = 50m,
                            Price50 = 85m,
                            Title = "Book5"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Waqas Nazir6",
                            Description = "This is my sixth book",
                            ISBN = "SW4345355435",
                            ListPrice = 99m,
                            Price = 90m,
                            Price100 = 50m,
                            Price50 = 85m,
                            Title = "Book6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
